version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Installing dependencies..."
      - dotnet restore

  pre_build:
    commands:
      - echo "Running pre-build steps..."
      - dotnet tool restore
      - dotnet build -c Release

  build:
    commands:
      - echo "Publishing the application..."
      - dotnet publish -c Release -o ./publish

  post_build:
    commands:
      - echo "Build and publish completed on `date`."
      - echo "Zipping the published output..."
      - zip -r publish.zip ./publish

artifacts:
  files:
    - publish.zip
    - appspec.yml
    - scripts/**/*
